"""
GitHub Data Export Module
Handles: caching scraped data as JSON, generating PDF and Word reports.
"""
import os
import json
from datetime import datetime


def get_github_data_dir(user_id=None):
    """Returns the directory for storing GitHub data per user."""
    if os.name == 'posix' and os.getenv('WEBSITE_SITE_NAME'):
        base = "/home/data/github_cache"
    else:
        base = "github_cache"

    if user_id:
        base = os.path.join(base, user_id)

    os.makedirs(base, exist_ok=True)
    return base


def get_cached_projects(user_id):
    """Load cached GitHub projects from JSON. Returns list or None."""
    data_dir = get_github_data_dir(user_id)
    cache_path = os.path.join(data_dir, "projects.json")
    if os.path.exists(cache_path):
        try:
            with open(cache_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            return data.get("projects", []), data.get("scraped_at", ""), data.get("profile_url", "")
        except Exception:
            pass
    return None, None, None


def save_projects_cache(user_id, projects, profile_url):
    """Save scraped GitHub projects to JSON cache."""
    data_dir = get_github_data_dir(user_id)
    cache_path = os.path.join(data_dir, "projects.json")
    data = {
        "profile_url": profile_url,
        "scraped_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "project_count": len(projects),
        "projects": projects
    }
    with open(cache_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    return cache_path


def generate_word_report(user_id, projects, profile_url):
    """Generate a Word (.docx) report of GitHub projects."""
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Title
    title = doc.add_heading('GitHub Projects Portfolio', level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = RGBColor(124, 58, 237)

    # Profile Info
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(f"Profile: {profile_url}")
    run.font.size = Pt(11)
    run.font.color.rgb = RGBColor(100, 116, 139)

    p2 = doc.add_paragraph()
    p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run2 = p2.add_run(f"Generated: {datetime.now().strftime('%B %d, %Y')}")
    run2.font.size = Pt(10)
    run2.font.color.rgb = RGBColor(148, 163, 184)

    doc.add_paragraph()  # Spacer

    # Projects
    for i, proj in enumerate(projects, 1):
        name = proj.get("name", "Untitled")
        url = proj.get("url", "")
        summary = proj.get("summary", "No summary available.")

        # Project heading
        heading = doc.add_heading(f"{i}. {name}", level=2)
        for run in heading.runs:
            run.font.color.rgb = RGBColor(6, 182, 212)

        # URL
        p_url = doc.add_paragraph()
        run_url = p_url.add_run(f"🔗 {url}")
        run_url.font.size = Pt(10)
        run_url.font.color.rgb = RGBColor(100, 116, 139)

        # Summary content
        doc.add_heading('Repository Summary', level=3)
        # Truncate long summaries just in case
        summary_text = summary[:3000] if summary else "No summary available."
        if len(summary) > 3000:
            summary_text += "\n\n... (truncated)"

        for line in summary_text.split('\n'):
            line = line.strip()
            if line:
                p = doc.add_paragraph(line)
                p.paragraph_format.space_after = Pt(4)
                for run in p.runs:
                    run.font.size = Pt(10)

        doc.add_paragraph()  # Spacer between projects

    # Footer
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer_p.add_run("Generated by JobFlow AI")
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(148, 163, 184)

    # Save
    data_dir = get_github_data_dir(user_id)
    file_path = os.path.join(data_dir, "GitHub_Projects_Portfolio.docx")
    doc.save(file_path)
    return file_path


def generate_pdf_report(user_id, projects, profile_url):
    """Generate a PDF report of GitHub projects."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER

    data_dir = get_github_data_dir(user_id)
    file_path = os.path.join(data_dir, "GitHub_Projects_Portfolio.pdf")

    doc = SimpleDocTemplate(file_path, pagesize=A4,
                            topMargin=25 * mm, bottomMargin=20 * mm,
                            leftMargin=20 * mm, rightMargin=20 * mm)

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle('CustomTitle', parent=styles['Title'],
                                 textColor=HexColor('#7c3aed'),
                                 fontSize=22, spaceAfter=10,
                                 alignment=TA_CENTER)

    subtitle_style = ParagraphStyle('Subtitle', parent=styles['Normal'],
                                    textColor=HexColor('#64748b'),
                                    fontSize=10, alignment=TA_CENTER,
                                    spaceAfter=6)

    project_title_style = ParagraphStyle('ProjectTitle', parent=styles['Heading2'],
                                         textColor=HexColor('#06b6d4'),
                                         fontSize=14, spaceBefore=16,
                                         spaceAfter=4)

    url_style = ParagraphStyle('URL', parent=styles['Normal'],
                               textColor=HexColor('#64748b'),
                               fontSize=9, spaceAfter=8)

    body_style = ParagraphStyle('Body', parent=styles['Normal'],
                                fontSize=10, leading=14,
                                textColor=HexColor('#334155'),
                                spaceAfter=4)

    readme_heading_style = ParagraphStyle('ReadmeH', parent=styles['Heading3'],
                                          textColor=HexColor('#475569'),
                                          fontSize=11, spaceBefore=6, spaceAfter=4)

    footer_style = ParagraphStyle('Footer', parent=styles['Normal'],
                                  textColor=HexColor('#94a3b8'),
                                  fontSize=8, alignment=TA_CENTER,
                                  spaceBefore=30)

    elements = []

    # Title
    elements.append(Paragraph("GitHub Projects Portfolio", title_style))
    elements.append(Paragraph(f"Profile: {profile_url}", subtitle_style))
    elements.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y')}", subtitle_style))
    elements.append(Spacer(1, 15))

    # Projects
    for i, proj in enumerate(projects, 1):
        name = proj.get("name", "Untitled")
        url = proj.get("url", "")
        summary = proj.get("summary", "No summary available.")

        elements.append(Paragraph(f"{i}. {name}", project_title_style))
        elements.append(Paragraph(f"🔗 {url}", url_style))
        elements.append(Paragraph("Repository Summary", readme_heading_style))

        # Truncate and clean summary
        summary_text = summary[:2000] if summary else "No summary available."
        if len(summary) > 2000:
            summary_text += "\n... (truncated)"

        # Clean special XML chars for reportlab
        summary_text = summary_text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')

        for line in summary_text.split('\n'):
            line = line.strip()
            if line:
                try:
                    elements.append(Paragraph(line, body_style))
                except Exception:
                    pass  # Skip problematic lines

        elements.append(Spacer(1, 12))

    elements.append(Paragraph("Generated by JobFlow AI", footer_style))

    doc.build(elements)
    return file_path
